/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "retrovision.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(retrovision_v1_Envelope, retrovision_v1_Envelope, 2)


PB_BIND(retrovision_v1_Hello, retrovision_v1_Hello, 2)


PB_BIND(retrovision_v1_HelloAck, retrovision_v1_HelloAck, 2)


PB_BIND(retrovision_v1_TimeSyncRequest, retrovision_v1_TimeSyncRequest, AUTO)


PB_BIND(retrovision_v1_TimeSyncResponse, retrovision_v1_TimeSyncResponse, AUTO)


PB_BIND(retrovision_v1_Observation, retrovision_v1_Observation, 2)


PB_BIND(retrovision_v1_WifiFrame, retrovision_v1_WifiFrame, 2)


PB_BIND(retrovision_v1_BleAdvertisement, retrovision_v1_BleAdvertisement, 2)


PB_BIND(retrovision_v1_GnssFix, retrovision_v1_GnssFix, AUTO)


PB_BIND(retrovision_v1_CustomObservation, retrovision_v1_CustomObservation, 2)


PB_BIND(retrovision_v1_Command, retrovision_v1_Command, 2)


PB_BIND(retrovision_v1_GetStatus, retrovision_v1_GetStatus, AUTO)


PB_BIND(retrovision_v1_Reboot, retrovision_v1_Reboot, AUTO)


PB_BIND(retrovision_v1_CommandAck, retrovision_v1_CommandAck, AUTO)


PB_BIND(retrovision_v1_Config, retrovision_v1_Config, 2)


PB_BIND(retrovision_v1_ChannelDwell, retrovision_v1_ChannelDwell, AUTO)


PB_BIND(retrovision_v1_WifiConfig, retrovision_v1_WifiConfig, 2)


PB_BIND(retrovision_v1_BleConfig, retrovision_v1_BleConfig, AUTO)


PB_BIND(retrovision_v1_RadioSchedule, retrovision_v1_RadioSchedule, AUTO)


PB_BIND(retrovision_v1_Status, retrovision_v1_Status, AUTO)


PB_BIND(retrovision_v1_Log, retrovision_v1_Log, AUTO)



















#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

