package dev.retrovision.core.map

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/** Fixtures generated by tools/make_map_fixtures.py with the reference Python pmtiles + mapbox-vector-tile libraries. */
class MapReadersTest {
    private fun res(name: String) = File(javaClass.classLoader!!.getResource("map/$name")!!.toURI())

    @Test fun tileIdsMatchReference() {
        assertEquals(0L, PmtilesReader.zxyToTileId(0, 0, 0))
        assertEquals(1L, PmtilesReader.zxyToTileId(1, 0, 0))
        assertEquals(2L, PmtilesReader.zxyToTileId(1, 0, 1))
        assertEquals(3L, PmtilesReader.zxyToTileId(1, 1, 1))
        assertEquals(4L, PmtilesReader.zxyToTileId(1, 1, 0))
        assertEquals(11L, PmtilesReader.zxyToTileId(2, 1, 3))
        assertEquals(19826287L, PmtilesReader.zxyToTileId(12, 2183, 1491))
        assertEquals(317220606L, PmtilesReader.zxyToTileId(14, 8735, 5966))
        assertEquals(1299669752853L, PmtilesReader.zxyToTileId(20, 557000, 380000))
    }

    @Test fun readsGzipTilesAndHeader() {
        PmtilesReader.open(res("small.pmtiles")).use { r ->
            assertEquals(TileType.MVT, r.info.type)
            assertEquals(0, r.info.minZoom)
            assertEquals(3, r.info.maxZoom)
            assertEquals(11.2, r.info.bounds[0], 1e-6)
            assertEquals(44.6, r.info.bounds[3], 1e-6)
            for (z in 0..3) for (x in 0 until (1 shl z)) for (y in 0 until (1 shl z)) {
                assertEquals("$z/$x/$y", String(r.tile(z, x, y)!!))
            }
            assertNull(r.tile(4, 0, 0))
            assertNull(r.tile(2, 9, 0))
        }
    }

    @Test fun followsLeafDirectories() {
        PmtilesReader.open(res("leafy.pmtiles")).use { r ->
            var n = 0
            for (z in 0..7) for (x in 0 until (1 shl z)) for (y in 0 until (1 shl z)) {
                assertEquals("$z/$x/$y", String(r.tile(z, x, y)!!)); n++
            }
            assertEquals(21845, n)
            assertNull(r.tile(8, 0, 0))
        }
    }

    @Test fun decodesMvt() {
        val layers = Mvt.decode(res("sample.mvt").readBytes()).associateBy { it.name }
        val road = layers.getValue("roads").features.single()
        assertEquals(Mvt.GeomType.LINESTRING, road.type)
        assertEquals("Via Emilia", road.str("name"))
        assertEquals(2.0, road.num("lanes")!!, 0.0)
        assertArrayEquals(floatArrayOf(0f, 0f, 100f, 100f, 200f, 50f), road.parts.single(), 0f)

        val water = layers.getValue("water").features.single()
        assertEquals(Mvt.GeomType.POLYGON, water.type)
        val ring = water.parts.single()
        assertEquals(10, ring.size) // 4 vertices + closing point
        assertEquals(ring[0], ring[8], 0f); assertEquals(ring[1], ring[9], 0f)
        assertEquals(1.5, water.num("area")!!, 1e-6)

        val place = layers.getValue("places").features.single()
        assertEquals(Mvt.GeomType.POINT, place.type)
        assertArrayEquals(floatArrayOf(300f, 400f), place.parts.single(), 0f)
        assertEquals(true, place.props["capital"])
        assertEquals(4096, layers.getValue("places").extent)
    }

    @Test fun mercatorRoundTrip() {
        val lat = 44.4949; val lon = 11.3426
        assertEquals(lat, WebMercator.lat(WebMercator.y(lat)), 1e-9)
        assertEquals(lon, WebMercator.lon(WebMercator.x(lon)), 1e-9)
        // Bologna is tile 14/8708/5926 per standard slippy-map maths
        assertEquals(8708, (WebMercator.x(lon) * (1 shl 14)).toInt())
        assertEquals(5926, (WebMercator.y(lat) * (1 shl 14)).toInt())
        assertTrue(WebMercator.metresPerUnit(lat) < 40_075_016.686)
    }
}
